version: '3'
services:
  node-app:
    build: .
    depends_on:
    - mongo
    container_name: nodejs
    ports:
      - "8080:8080"
    environment:
      MONGO_USER: "rania"
      MONGO_PASS: "Qwe123"
      MONGO_HOST: "mongo"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "rania"
      MONGO_INITDB_ROOT_PASSWORD: "Qwe123"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
